language: php

dist: xenial

git:
  depth: 5
  quiet: true

cache:
  directories:
  - $HOME/.composer
  - $HOME/.php-cs-fixer
  - vendor

php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4snapshot
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: 7.4snapshot
  - php: nightly
  - php: 7.4snapshot

install:
- composer update --no-interaction --no-progress --prefer-dist --optimize-autoloader $COMPOSER_FLAGS

script:
- vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml

after_script:
- mkdir -p "$HOME/.php-cs-fixer"
- vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --allow-risky true --diff --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)
