language: php

env:
  secure: "N51xNIgSMV36p8U6wdF3UweUMKN2R+pnyidUH6EO4RgE+5I5NugEOUfJdwolHinvubwM31oBCRFAyBL221cIw+XzxYe9SOIToonmuGW7wZcpYDAHSRtkUJNACTlPT1M3iH0H54lIPmVCh8/DEfrYHgNWBztMyg3YD512QTM45uc="

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

git:
  depth: 10

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer config --global github-oauth.github.com $GITHUB_TRAVIS_TOKEN
  - composer self-update --no-interaction --no-progress
  - composer install --no-interaction --no-progress --prefer-dist --profile -v

script:
  - vendor/bin/phpunit
